version: '3.1'

services:

    mysql:
      image: mysql:8
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE -> silently handles warnings
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_USER: root
      volumes: 
        - mysql-data:/var/lib/mysql
      networks: 
        - application-network

    api-server:
      depends_on:
        - mysql
      build:
        context: .
        dockerfile: Dockerfile
      image: myapplication
      ports: 
          - "8080:8080" ## Change if your port is different
      networks: 
        - application-network
      environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: database_development
        MYSQL_HOST: mysql
        SERVER_PORT: 8080 ## Change if your port is different

networks:
  application-network:
    driver: bridge
volumes: 
  mysql-data:
    driver: local
